const pageSectionToItem = {
  'second-language-classes': 'churchWide',
  'interest-groups': 'churchWide',
  'discipleship': 'discipleship',
  'announcements': 'announcements',
  'events': 'events',
  'upcoming-sermons': 'upcomingSermons',
  'im-new': 'imNew',
  'missions': 'missions',
  'our-history': 'ourHistory',
  'administrative': 'ourTeam',
  'ministry': 'ourTeam',
  'pastoral': 'ourTeam',
  'outreach': 'outreach',
  'english-service': 'services',
  'sunset-service-english-mandarin': 'services',
  'teo-chew-chinese-service': 'services',
  'statement-of-faith': 'statementOfFaith',
}

const pageSectionToPage = {
  'second-language-classes': 'church-wide',
  'interest-groups': 'church-wide',
  'discipleship': 'discipleship',
  'announcements': 'home',
  'events': 'home',
  'upcoming-sermons': 'home',
  'im-new': 'im-new',
  'missions': 'missions',
  'our-history': 'our-history',
  'administrative': 'our-team',
  'ministry': 'our-team',
  'pastoral': 'our-team',
  'outreach': 'outreach',
  'english-service': 'services',
  'sunset-service-english-mandarin': 'services',
  'teo-chew-chinese-service': 'services',
  'statement-of-faith': 'statement-of-faith',
}

const itemToPage = {
  'churchWide': 'church-wide',
  'discipleship': 'discipleship',
  'announcements': 'home',
  'events': 'home',
  'upcomingSermons': 'home',
  'imNew': 'im-new',
  'missions': 'missions',
  'ourHistory': 'our-history',
  'ourTeam': 'our-team',
  'outreach': 'outreach',
  'services': 'services',
  'statementOfFaith': 'statement-of-faith',
}

export {
  pageSectionToItem,
  pageSectionToPage,
  itemToPage,
}