import { ourTeam } from '../helper-files/images.js'
const {
  dongFan,
  ivanChow,
  jasmineLee,
  jennyAng,
  leonardLee,
  psLam,
  revAdrianLim,
  revChang,
  revJerryGoh,
  vincentLai,
  yeoChongNim,
} = ourTeam

const ourTeamData = [
  {
    itemId: 1,
    page:'our-team',
    sectionName: 'pastoral',
    title: 'Rev. Adrian Lim',
    text: 'Senior Pastor',
    imgSrc: revAdrianLim,
  },
  {
    itemId: 2,
    page:'our-team',
    sectionName: 'pastoral',
    title: 'Rev. Andrew Chang',
    text: 'Interim Pastoral Advisor of Teochew/Chinese Congregation',
    imgSrc: revChang,
  },
  {
    itemId: 3,
    page:'our-team',
    sectionName: 'pastoral',
    title: 'Rev. Dr. Jerry Goh',
    text: 'Pastor of English Congregation',
    imgSrc: revJerryGoh,
  },
  {
    itemId: 4,
    page:'our-team',
    sectionName: 'pastoral',
    title: 'Ps. Lam Yuen Foong',
    text: 'Pastor of Sunset Congregation',
    imgSrc: psLam,
  },
  {
    itemId: 5,
    page:'our-team',
    sectionName: 'ministry',
    title: 'Mr. Yeo Chong Nim',
    text: 'Outreach Ministry',
    imgSrc: yeoChongNim,
  },
  {
    itemId: 6,
    page:'our-team',
    sectionName: 'ministry',
    title: 'Ms. Jenny Ang ',
    text: 'Children\'s Outreach Ministry',
    imgSrc: jennyAng,
  },
  {
    itemId: 7,
    page:'our-team',
    sectionName: 'administrative',
    title: 'Mr. Leonard Lee',
    text: 'Administration Manager',
    imgSrc: leonardLee,
  },
  {
    itemId: 8,
    page:'our-team',
    sectionName: 'administrative',
    title: 'Mr. Vincent Lai Seck Tong',
    text: 'Administrative Executive (Facilities & Maintenance)',
    imgSrc: vincentLai,
  },
  {
    itemId: 9,
    page:'our-team',
    sectionName: 'administrative',
    title: 'Ms. Jasmine Lee',
    text: 'Administrative Executive',
    imgSrc: jasmineLee,
  },
  {
    itemId: 10,
    page:'our-team',
    sectionName: 'administrative',
    title: 'Mr. Dong Fan',
    text: 'Administrative Executive ',
    imgSrc: dongFan,
  },
  {
    itemId: 11,
    page:'our-team',
    sectionName: 'administrative',
    title: 'Mr. Ivan Chow',
    text: 'Church Caretaker',
    imgSrc: ivanChow,
  },
]

export default ourTeamData